config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # resources :meetings do
  #   resources :recordings
  # end

  resources :meetings, :recordings

  root to: 'meetings#index'

  # ACCESSING CALLBACK FROM BBB API WHEN RECORDING IS PROCESSED
  get '/destroy_recording', to: 'recordings#destroy_recording'
  get '/publish',           to: 'recordings#publish'

  # get 'auth/google', as: 'google_login'
  # get '/auth/:provider/callback', to: 'sessions#update'
end

app/models/meeting.rb
# frozen_string_literal: true

class Meeting < ApplicationRecord
  has_one :recording
end

app/controllers/meetings_controller.rb
# frozen_string_literal: true

class MeetingsController < ApplicationController
  include BbbHelper

  require 'securerandom'

  before_action :set_meeting, only: %i[show edit update destroy]

  helper :meetings
  # helper_method :initialize_meeting_id, :initialize_meeting_password

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.all

    get_recordings
  end

  # GET /meetings/1 or /meetings/1.json
  def show; end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit; end

  # CREATE MEETING ON BBB SERVER USING BBB API
  def create_meeting
    create_options = {
      welcome: @meeting.welcome_message,
      record: @meeting.meeting_record,
      attendeePW: @meeting.attendee_password,
      moderatorPW: @meeting.moderator_password
    }

    # APPENDS API CALLBACK URL IF RECORDING IS SELECTED
    if @meeting.meeting_record
      create_options['meta_bbb-recording-ready-url'] = 'https%3A%2F%2Fbbb.samuel.blindside-dev.com%2Frecordings'
    end

    bbb.create_meeting(@meeting.name, @meeting.external_meeting_id, create_options)
  end

  # JOIN MEETING ON BBB SERVER USING BBB API
  def join_meeting
    bbb.join_meeting_url(@meeting.external_meeting_id, current_user.name, @meeting.moderator_password)
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        create_meeting

        format.html do
          redirect_to join_meeting,
                      notice: 'Meeting was successfully created.'
        end

      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to meeting_url(@meeting), notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def meeting_params
    params.require(:meeting).permit(:external_meeting_id, :name, :welcome_message, :meeting_record, :moderator_password,
                                    :attendee_password)
  end
end

app/helpers/meetings_helper.rb
# frozen_string_literal: true

module MeetingsHelper
  # Generates a GUID value for BBB MeetingID
  def initialize_meeting_id
    SecureRandom.uuid
  end

  def initialize_meeting_password
    SecureRandom.hex(4)
  end
end

app/views/meetings/_form.haml
= console
= form_with(model: meeting, local: true) do |form|
  - if meeting.errors.any?
    #error_explanation
      %h2
        = pluralize(meeting.errors.count, "error")
        prohibited this meeting from being saved:
      %ul
        - meeting.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name, :value => "#{current_user.name}'s meeting"

  .field
    = form.label :welcome_message
    = form.text_area :welcome_message

  .field
    = form.label :meeting_record, 'Do you want the meeting to be recorded?'
    = form.check_box :meeting_record

  .field
    = form.text_field :external_meeting_id, :value => initialize_meeting_id, readonly: true

  .field
    = form.label :moderator_password
    = form.text_field :moderator_password, :value => initialize_meeting_password, readonly: true

  .field
    = form.label :attendee_password
    = form.text_field :attendee_password, :value => initialize_meeting_password, readonly: true

  .actions
    = form.submit

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.haml
=console
%p#notice= notice
%h1 My Meetings


- if Meeting.all.empty? && current_user == nil
  = "There are no meetings. Please"
  = link_to 'sign in', new_user_session_path
  = "to create a meeting."

- else
  %table
    %thead
      %tr
        %th Meeting Name
        %th Welcome Message
        %th Is the meeting being recorded?
        %th ID
        %th{:colspan => "3"}
    %tbody
      - @meetings.each do |meeting|
        %tr
          %td= meeting.name
          %td= meeting.welcome_message
          %td= meeting.meeting_record
          %td= meeting.external_meeting_id

          %td= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' }
  %br/

  = link_to 'New Meeting', new_meeting_path

%br
%br

%h1#recording All Recordings
%table
  %thead
    %tr
      %th Recording
      %th Meeting
      %th State
      %th Publish
      %th{:colspan => "3"}
  %tbody
    - @recordings.each do |recording|
      %tr
        %td= recording.recording_id
        %td= recording.meeting_id
        %td= recording.meeting_state

        -# this needs to be replaced by ruby/js insertAdjacentHTML
        -# %td#publish_state
        %td.publish_state= recording.publish

        %td= link_to 'Publish/Unpublish', publish_path(:recording_id => recording.recording_id, :publish => recording.publish)

        %td= link_to 'Destroy', destroy_recording_path(:recording_id => recording.recording_id)

%br/

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting, current_user: current_user %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Meetingid:</strong>
  <%= @meeting.external_meeting_id %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>