config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # resources :meetings do
  #   resources :recordings
  # end

  resources :meetings, :recordings

  root to: 'meetings#index'

  # ACCESSING CALLBACK FROM BBB API WHEN RECORDING IS PROCESSED
  get '/destroy_recording', to: 'recordings#destroy_recording'
  get '/publish',           to: 'recordings#publish'

  # get 'auth/google', as: 'google_login'
  # get '/auth/:provider/callback', to: 'sessions#update'
end

app/models/recording.rb
# frozen_string_literal: true

class Recording < ApplicationRecord
  belongs_to :meeting

  validates :recording_id, uniqueness: true
end

app/controllers/recordings_controller.rb
# frozen_string_literal: true

class RecordingsController < ApplicationController
  include BbbHelper

  before_action :set_recording, only: %i[show edit update destroy]

  # GET /recordings or /recordings.json
  def index
    get_recordings
  end

  def get_recordings
    @recordings = []

    bbb.get_recordings[:recordings].each_with_index do |recording, _i|
      @recording = Recording.new
      @recording.recording_id = recording[:recordID]
      @recording.meeting_id = recording[:meetingID]
      @recording.meeting_state = recording[:state]
      @recording.publish = recording[:published]
      @recordings.push(@recording)
    end
  end

  # GET /recordings/1 or /recordings/1.json
  def show; end

  # GET /recordings/new
  def new
    @recording = Recording.new
  end

  # GET /recordings/1/edit
  def edit; end

  def create
    @recording = Recording.new(recording_params)

    respond_to do |format|
      if @recording.save
        redirect_to @recording, notice: 'Recording has been created.'

      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recordings/1 or /recordings/1.json
  def update
    respond_to do |format|
      if @recording.update(recording_params)
        format.html { redirect_to recording_url(@recording), notice: 'Recording was successfully updated.' }
        format.json { render :show, status: :ok, location: @recording }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy_recording
    @recording = params[:recording_id]
    bbb.delete_recordings(@recording)

    redirect_to root_path
  end

  def publish
    # recording = Recording.find(params[:recording_id])
    @recording = params[:recording_id]
    @publish = params[:publish]

    # infinite loop here?
    # TODO finish AJAX integration
    case @publish.to_s
    when 'true'
      bbb.publish_recordings(@recording, false)
    when 'false'
      bbb.publish_recordings(@recording, true)
    end

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  # DELETE /recordings/1 or /recordings/1.json
  def destroy
    respond_to do |format|
      format.html { redirect_to destroy_recording, notice: 'Recording was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recording
    @recording = Recording.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recording_params
    params.require(:recording).permit(:id, :recording_id, :meeting_id, :meeting_state, :publish)
  end
end

app/helpers/recordings_helper.rb
# frozen_string_literal: true

module RecordingsHelper
end

app/views/recordings/_form.html.erb
<%= form_with(model: recording, local: true) do |form| %>
  <% if recording.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recording.errors.count, "error") %> prohibited this recording from being saved:</h2>

      <ul>
        <% recording.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recording_id %>
    <%= form.text_field :recording_id %>
  </div>

  <div class="field">
    <%= form.label :meeting_id %>
    <%= form.text_field :meeting_id %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :publish %>
    <%= form.check_box :publish %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recordings/edit.html.erb
<h1>Editing Recording</h1>

<%= render 'form', recording: @recording %>

<%= link_to 'Show', @recording %> |
<%= link_to 'Back', recordings_path %>

app/views/recordings/index.haml
= console

%p#notice= notice
%h1#recording Recordings
%table
  %thead
    %tr
      %th Recording
      %th Meeting
      %th State
      %th Publish
      %th{:colspan => "3"}
  %tbody
    - @recordings.each do |recording|
      %tr
        %td= recording.recording_id
        %td= recording.meeting_id
        %td= recording.meeting_state

        -# this needs to be replaced by ruby/js insertAdjacentHTML
        -# %td#publish_state
        %td.publish_state= recording.publish

        %td= link_to 'Publish/Unpublish', publish_path(:recording_id => recording.recording_id, :publish => recording.publish)

        %td= link_to 'Destroy', destroy_recording_path(:recording_id => recording.recording_id)


%br/

= link_to "All Meetings", meetings_path

app/views/recordings/new.html.erb
<h1>New Recording</h1>

<%= render 'form', recording: @recording %>

<%= link_to 'Back', recordings_path %>

app/views/recordings/publish.js.erb
  console.log("hey")
  var publish_state = document.querySelector(".publish_state");
  publish_state.insertAdjacentHTML("afterbegin", "<%= j @publish %>");

app/views/recordings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recording:</strong>
  <%= @recording.recording_id %>
</p>

<p>
  <strong>Meeting:</strong>
  <%= @recording.meeting_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @recording.state %>
</p>

<p>
  <strong>Publish:</strong>
  <%= @recording.publish %>
</p>

<%= link_to 'Edit', edit_recording_path(@recording) %> |
<%= link_to 'Back', recordings_path %>